# Generated by Django 5.0 on 2024-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("name", models.TextField()),
                ("nz", models.TextField()),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("key", models.TextField()),
                ("iso", models.TextField()),
            ],
            options={
                "db_table": "stations",
            },
        ),
    ]
