# Generated by Django 5.0 on 2023-12-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("nz", models.TextField()),
                ("id", models.IntegerField()),
                ("key", models.TextField()),
                ("iso", models.TextField()),
            ],
            options={
                "db_table": "stations",
            },
        ),
    ]
