# Generated by Django 5.0 on 2024-01-08 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "locations",
            },
        ),
    ]
